# Generated by Django 5.2.4 on 2025-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id'], name='shop_catego_id_d67477_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'created'], name='shop_produc_availab_388fee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'available'], name='shop_produc_categor_322d96_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='shop_produc_price_3b79b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='shop_produc_created_661b12_idx'),
        ),
    ]
